CREATE EXTERNAL TABLE IF NOT EXISTS `TW_SONG_BASEINFO_D`(
    `NBR` string,
    `NAME` string,
    `SOURCE` int,
    `ALBUM` string,
    `PRDCT` string,
    `LANG` string,
    `VIDEO_FORMAT` string,
    `DUR` int,
    `SINGER1` string,
    `SINGER2` string,
    `SINGER1ID` string,
    `SINGER2ID` string,
    `MAC_TIME` int,
    `POST_TIME` string,
    `PINYIN_FST` string,
    `PINYIN` string,
    `SING_TYPE` int,
    `ORI_SINGER` string,
    `LYRICIST` string,
    `COMPOSER` string,
    `BPM_VAL` int,
    `STAR_LEVEL` int,
    `VIDEO_QLTY` int,
    `VIDEO_MK` int,
    `VIDEO_FTUR` int,
    `LYRIC_FTUR` int,
    `IMG_QLTY` int,
    `SUBTITLES_TYPE` int,
    `AUDIO_FMT` int,
    `ORI_SOUND_QLTY` int,
    `ORI_TRK` int,
    `ORI_TRK_VOL` int,
    `ACC_VER` int,
    `ACC_QLTY` int,
    `ACC_TRK_VOL` int,
    `ACC_TRK` int,
    `WIDTH` int,
    `HEIGHT` int,
    `VIDEO_RSVL` int,
    `SONG_VER` int,
    `AUTH_CO` string,
    `STATE` int,
    `PRDCT_TYPE` array<string>
) partitioned by (data_dt string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
STORED AS PARQUET
LOCATION 'hdfs://node01/user/hive/warehouse/music.db/TW_SONG_BASEINFO_D';